timezone: America/Los_Angeles
encoding: utf-8
url: "https://kfaizi.github.io"
description: "Personal website of Kian Faizi."
plugins:
  - jemoji
collections:
  posts:
    permalink: /blog/:slug:output_ext
# github defaults
lsi: false
safe: true
source: .
incremental: false
gist:
  noscript: false
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
