timezone: America/Los_Angeles
encoding: utf-8
url: "https://kfaizi.github.io"
description: "Kian Faizi's personal website"
twitter: kianfaizi

# github defaults
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
